### ISSUE TITLE
How to get cloth keypoints files and cloth parsing files in UvitonDatasetV19_test?

### ISSUE THREAD

**Issue by zealota** [xiezhy6/PASTA-GAN#10]
It seems this files only use for test dataset. 
MPV and UPT dataset doesn't include that files.
Can you provide that ?

**Comment by xiezhy6** [comment]
Hi, we use [openpose](UvitonDatasetV19_test) to obtain the 18-channel keypoints and [graphonomy](https://github.com/Gaoyiminggithub/Graphonomy) to obtain the human parsing.

**Comment by zealota** [comment]
Does you mean the cloth keypoints get from openpose results and selected? 
and the cloth parsing files are also similar way?

**Comment by xiezhy6** [comment]
Yes, though they are named "cloth parsing" and "cloth keypoints", they actually refer to the keypoints and human parsing of the model that provided the garment to be transferred.
